### ISSUE TITLE
Suggest renaming Reference page to Concepts, and redirecting the old URL to the new

### ISSUE THREAD

**Issue by claremacrae** [SkepticMystic/breadcrumbs-docs#1]
### Summary

I think the Reference page has very useful content, but it sounded to me like it was 'stuff to go to for a quick reminder after I already know stuff...

Its intro is:

> This page defines various concepts used across Breadcrumbs

Which works really well.

So I think it would be helpful to rename **Reference** to **Concepts**.

### Mechanics

Publish has a redirect mechanism.

Here is how I documented using it for the Tasks plugin docs:

[Redirects - Renaming files and headings](https://publish.obsidian.md/tasks-contributing/Documentation/Redirects+-+Renaming+files)

The template mentioned is:

[file path for redirecting alias.md](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/docs/_meta/templates/file%20path%20for%20redirecting%20alias.md)

**Comment by SkepticMystic** [comment]
Thanks Clare!
I agree with the issue, and the info you shared in really helpful for future, as well :)
